# This file is copied to spec/ when you run 'rails generate rspec:install'
require 'simplecov'
SimpleCov.start

require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'
# Add additional requires below this line. Rails is not loaded until this point!

# Requires supporting ruby files with custom matchers and macros, etc, in
# spec/support/ and its subdirectories. Files matching `spec/**/*_spec.rb` are
# run as spec files by default. This means that files in spec/support that end
# in _spec.rb will both be required and run as specs, causing the specs to be
# run twice. It is recommended that you do not name files matching this glob to
# end with _spec.rb. You can configure this pattern with the --pattern
# option on the command line or in ~/.rspec, .rspec or `.rspec-local`.
#
# The following line is provided for convenience purposes. It has the downside
# of increasing the boot-up time by auto-requiring all files in the support
# directory. Alternatively, in the individual `*_spec.rb` files, manually
# require only the support files necessary.
#
# Dir[Rails.root.join('spec', 'support', '**', '*.rb')].sort.each { |f| require f }

# Checks for pending migrations and applies them before tests are run.
# If you are not using ActiveRecord, you can remove these lines.
begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  abort e.to_s.strip
end
RSpec.configure do |config|
  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  config.fixture_path = "#{::Rails.root}/spec/fixtures"

  # If you're not using ActiveRecord, or you'd prefer not to run each of your
  # examples within a transaction, remove the following line or assign false
  # instead of true.
  config.use_transactional_fixtures = true

  # You can uncomment this line to turn off ActiveRecord support entirely.
  # config.use_active_record = false

  # RSpec Rails can automatically mix in different behaviours to your tests
  # based on their file location, for example enabling you to call `get` and
  # `post` in specs under `spec/controllers`.
  #
  # You can disable this behaviour by removing the line below, and instead
  # explicitly tag your specs with their type, e.g.:
  #
  #     RSpec.describe UsersController, type: :controller do
  #       # ...
  #     end
  #
  # The different available types are documented in the features, such as in
  # https://rspec.info/features/6-0/rspec-rails
  config.infer_spec_type_from_file_location!

  # Filter lines from Rails gems in backtraces.
  config.filter_rails_from_backtrace!
  # arbitrary gems may also be filtered via:
  # config.filter_gems_from_backtrace("gem name")
end

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
     with.test_framework :rspec
     with.library :rails
  end
end

def movie_stub
  {
    "adult": false,
    "backdrop_path": "/oMsxZEvz9a708d49b6UdZK1KAo5.jpg",
    "budget": 63000000,
    "genres": [
        {
            "id": 28,
            "name": "Action"
        },
        {
            "id": 878,
            "name": "Science Fiction"
        }
    ],
    "homepage": "http://www.warnerbros.com/matrix",
    "id": 603,
    "imdb_id": "tt0133093",
    "original_language": "en",
    "original_title": "The Matrix",
    "overview": "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    "popularity": 78.056,
    "poster_path": "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    "release_date": "1999-03-30",
    "revenue": 463517383,
    "runtime": 136,
    "status": "Released",
    "tagline": "Welcome to the Real World.",
    "title": "The Matrix",
    "video": false,
    "vote_average": 8.2,
    "vote_count": 23409
  }
end

def cast_stub
  {
    :id=>221,
    :cast=>
     [{:adult=>false,
       :gender=>2,
       :id=>2749,
       :known_for_department=>"Acting",
       :name=>"James Dean",
       :original_name=>"James Dean",
       :popularity=>11.552,
       :profile_path=>"/5oaDvEoQssXlDt1KSQVl0M4rgBn.jpg",
       :cast_id=>6,
       :character=>"Jim Stark",
       :credit_id=>"52fe4228c3a36847f8008765",
       :order=>0},
      {:adult=>false,
       :gender=>1,
       :id=>2769,
       :known_for_department=>"Acting",
       :name=>"Natalie Wood",
       :original_name=>"Natalie Wood",
       :popularity=>11.63,
       :profile_path=>"/tmYB8aXfb5fe2K1wquhRLfMGViu.jpg",
       :cast_id=>7,
       :character=>"Judy",
       :credit_id=>"52fe4228c3a36847f8008769",
       :order=>1},
      {:adult=>false,
       :gender=>2,
       :id=>2770,
       :known_for_department=>"Acting",
       :name=>"Sal Mineo",
       :original_name=>"Sal Mineo",
       :popularity=>7.361,
       :profile_path=>"/glfs6BXlFIMprrJSuiT74VzJIOJ.jpg",
       :cast_id=>8,
       :character=>"John 'Plato' Crawford",
       :credit_id=>"52fe4228c3a36847f800876d",
       :order=>2},
      {:adult=>false,
       :gender=>2,
       :id=>2771,
       :known_for_department=>"Acting",
       :name=>"Jim Backus",
       :original_name=>"Jim Backus",
       :popularity=>4.637,
       :profile_path=>"/9jCwiBAPyYdngUx2aKHZqSvrbHS.jpg",
       :cast_id=>10,
       :character=>"Frank Stark",
       :credit_id=>"52fe4228c3a36847f8008775",
       :order=>3},
      {:adult=>false,
       :gender=>1,
       :id=>2772,
       :known_for_department=>"Acting",
       :name=>"Ann Doran",
       :original_name=>"Ann Doran",
       :popularity=>8.141,
       :profile_path=>"/t6q0svIGjotyJQgxr74pKz6462g.jpg",
       :cast_id=>9,
       :character=>"Carol Stark",
       :credit_id=>"52fe4228c3a36847f8008771",
       :order=>4},
      {:adult=>false,
       :gender=>2,
       :id=>2775,
       :known_for_department=>"Directing",
       :name=>"Corey Allen",
       :original_name=>"Corey Allen",
       :popularity=>1.86,
       :profile_path=>"/tdZjPHg5DJsX3BJzWDQXwN4qWKv.jpg",
       :cast_id=>14,
       :character=>"Buzz Gunderson",
       :credit_id=>"52fe4228c3a36847f800878b",
       :order=>5},
      {:adult=>false,
       :gender=>2,
       :id=>2776,
       :known_for_department=>"Acting",
       :name=>"William Hopper",
       :original_name=>"William Hopper",
       :popularity=>10.66,
       :profile_path=>"/fOYuQ914CheBCDEHdTDoCsmjhTI.jpg",
       :cast_id=>15,
       :character=>"Judy's Father",
       :credit_id=>"52fe4228c3a36847f800878f",
       :order=>6},
      {:adult=>false,
       :gender=>1,
       :id=>2777,
       :known_for_department=>"Acting",
       :name=>"Rochelle Hudson",
       :original_name=>"Rochelle Hudson",
       :popularity=>2.845,
       :profile_path=>"/sJFm49AMpqIDosigOTWTo5CQ2SG.jpg",
       :cast_id=>16,
       :character=>"Judy's Mother",
       :credit_id=>"52fe4228c3a36847f8008793",
       :order=>7},
      {:adult=>false,
       :gender=>2,
       :id=>2778,
       :known_for_department=>"Acting",
       :name=>"Dennis Hopper",
       :original_name=>"Dennis Hopper",
       :popularity=>10.18,
       :profile_path=>"/3Hg8mkb1RxqNhDOofzHdr0PoufH.jpg",
       :cast_id=>17,
       :character=>"Goon",
       :credit_id=>"52fe4228c3a36847f8008797",
       :order=>8},
      {:adult=>false,
       :gender=>2,
       :id=>2646,
       :known_for_department=>"Acting",
       :name=>"Edward Platt",
       :original_name=>"Edward Platt",
       :popularity=>6.195,
       :profile_path=>"/uVl1ZzKXkvJSTHVYyfNriMV8BNV.jpg",
       :cast_id=>18,
       :character=>"Ray Fremick",
       :credit_id=>"52fe4228c3a36847f800879b",
       :order=>9},
      {:adult=>false,
       :gender=>1,
       :id=>2779,
       :known_for_department=>"Acting",
       :name=>"Steffi Sidney",
       :original_name=>"Steffi Sidney",
       :popularity=>1.048,
       :profile_path=>"/eE1u9d9iqy419JKqbCHGkP2POSC.jpg",
       :cast_id=>19,
       :character=>"Mil",
       :credit_id=>"52fe4228c3a36847f800879f",
       :order=>10},
      {:adult=>false,
       :gender=>1,
       :id=>2790,
       :known_for_department=>"Acting",
       :name=>"Marietta Canty",
       :original_name=>"Marietta Canty",
       :popularity=>2.11,
       :profile_path=>"/rfJaehAVzXraDrIu3oHLjy6QxOS.jpg",
       :cast_id=>33,
       :character=>"Crawford Maid",
       :credit_id=>"52fe4228c3a36847f80087d3",
       :order=>11},
      {:adult=>false,
       :gender=>1,
       :id=>2780,
       :known_for_department=>"Acting",
       :name=>"Virginia Brissac",
       :original_name=>"Virginia Brissac",
       :popularity=>3.883,
       :profile_path=>"/plkkPOoTu5qc6i1K9wRJXyoUgq2.jpg",
       :cast_id=>20,
       :character=>"Jim's Grandmother",
       :credit_id=>"52fe4228c3a36847f80087a3",
       :order=>12},
      {:adult=>false,
       :gender=>1,
       :id=>2781,
       :known_for_department=>"Acting",
       :name=>"Beverly Long",
       :original_name=>"Beverly Long",
       :popularity=>0.697,
       :profile_path=>nil,
       :cast_id=>21,
       :character=>"Helen",
       :credit_id=>"52fe4228c3a36847f80087a7",
       :order=>13},
      {:adult=>false,
       :gender=>2,
       :id=>2782,
       :known_for_department=>"Acting",
       :name=>"Ian Wolfe",
       :original_name=>"Ian Wolfe",
       :popularity=>5.332,
       :profile_path=>"/8Eum5GDti8Zh9ZyYSvWaoIHt8Wr.jpg",
       :cast_id=>22,
       :character=>"Dr. Minton",
       :credit_id=>"52fe4228c3a36847f80087ab",
       :order=>14},
      {:adult=>false,
       :gender=>2,
       :id=>2783,
       :known_for_department=>"Editing",
       :name=>"Frank Mazzola",
       :original_name=>"Frank Mazzola",
       :popularity=>0.703,
       :profile_path=>nil,
       :cast_id=>23,
       :character=>"Crunch",
       :credit_id=>"52fe4228c3a36847f80087af",
       :order=>15},
      {:adult=>false,
       :gender=>2,
       :id=>2784,
       :known_for_department=>"Acting",
       :name=>"Robert Foulk",
       :original_name=>"Robert Foulk",
       :popularity=>1.621,
       :profile_path=>"/jrJcoyksfLvnHgthmQHba2gwKWK.jpg",
       :cast_id=>24,
       :character=>"Gene",
       :credit_id=>"52fe4228c3a36847f80087b3",
       :order=>16},
      {:adult=>false,
       :gender=>2,
       :id=>2785,
       :known_for_department=>"Acting",
       :name=>"Jack Simmons",
       :original_name=>"Jack Simmons",
       :popularity=>0.764,
       :profile_path=>nil,
       :cast_id=>25,
       :character=>"Cookie",
       :credit_id=>"52fe4228c3a36847f80087b7",
       :order=>17},
      {:adult=>false,
       :gender=>2,
       :id=>1562727,
       :known_for_department=>"Acting",
       :name=>"Tom Bernard",
       :original_name=>"Tom Bernard",
       :popularity=>0.6,
       :profile_path=>nil,
       :cast_id=>65,
       :character=>"Harry",
       :credit_id=>"60d7264f6c0b360047ce69a4",
       :order=>18},
      {:adult=>false,
       :gender=>2,
       :id=>2787,
       :known_for_department=>"Acting",
       :name=>"Nick Adams",
       :original_name=>"Nick Adams",
       :popularity=>5.898,
       :profile_path=>"/wNXgXtq9m79bWNdS59y1anMcdIO.jpg",
       :cast_id=>27,
       :character=>"Chick",
       :credit_id=>"52fe4228c3a36847f80087bb",
       :order=>19},
      {:adult=>false,
       :gender=>2,
       :id=>2788,
       :known_for_department=>"Acting",
       :name=>"Jack Grinnage",
       :original_name=>"Jack Grinnage",
       :popularity=>2.619,
       :profile_path=>"/s2iMLwqgz717VQQTb46hF6GO21j.jpg",
       :cast_id=>28,
       :character=>"Moose",
       :credit_id=>"52fe4228c3a36847f80087bf",
       :order=>20},
      {:adult=>false,
       :gender=>2,
       :id=>2789,
       :known_for_department=>"Acting",
       :name=>"Clifford Morris",
       :original_name=>"Clifford Morris",
       :popularity=>0.6,
       :profile_path=>nil,
       :cast_id=>29,
       :character=>"Cliff",
       :credit_id=>"52fe4228c3a36847f80087c3",
       :order=>21},
      {:adult=>false,
       :gender=>1,
       :id=>107678,
       :known_for_department=>"Acting",
       :name=>"Almira Sessions",
       :original_name=>"Almira Sessions",
       :popularity=>1.774,
       :profile_path=>"/pQC9t4rOPGmUqwD4JdV2D2xpvch.jpg",
       :cast_id=>34,
       :character=>"Planetarium Teacher (uncredited)",
       :credit_id=>"52fe4228c3a36847f80087d7",
       :order=>22},
      {:adult=>false,
       :gender=>2,
       :id=>98450,
       :known_for_department=>"Acting",
       :name=>"Paul Birch",
       :original_name=>"Paul Birch",
       :popularity=>5.608,
       :profile_path=>"/elUNlCDIIXhXFc1LZbYr5cV3V2T.jpg",
       :cast_id=>35,
       :character=>"Police Lieutenant (uncredited)",
       :credit_id=>"52fe4228c3a36847f80087db",
       :order=>23},
      {:adult=>false,
       :gender=>1,
       :id=>1234545,
       :known_for_department=>"Acting",
       :name=>"Dorothy Abbott",
       :original_name=>"Dorothy Abbott",
       :popularity=>1.623,
       :profile_path=>"/bheDciblNfOsKTvRNRyWJ5BNUJS.jpg",
       :cast_id=>36,
       :character=>"Nurse (uncredited)",
       :credit_id=>"55ee1c679251413e4501634c",
       :order=>24},
      {:adult=>false,
       :gender=>2,
       :id=>94320,
       :known_for_department=>"Acting",
       :name=>"Jimmy Baird",
       :original_name=>"Jimmy Baird",
       :popularity=>2.752,
       :profile_path=>nil,
       :cast_id=>37,
       :character=>"Beau (uncredited)",
       :credit_id=>"55ee1cbcc3a3682c5d0184b4",
       :order=>25},
      {:adult=>false,
       :gender=>2,
       :id=>34609,
       :known_for_department=>"Acting",
       :name=>"Paul Bryar",
       :original_name=>"Paul Bryar",
       :popularity=>2.771,
       :profile_path=>"/o13k57tZuq5JZCRxHoNX0adOrcD.jpg",
       :cast_id=>38,
       :character=>"Desk Sergeant #2 (uncredited)",
       :credit_id=>"55ee1d04c3a36871bf000d04",
       :order=>26},
      {:adult=>false,
       :gender=>2,
       :id=>121260,
       :known_for_department=>"Acting",
       :name=>"John Close",
       :original_name=>"John Close",
       :popularity=>0.98,
       :profile_path=>nil,
       :cast_id=>39,
       :character=>"Police Officer (uncredited)",
       :credit_id=>"55ee1d25c3a3682c5d0184c1",
       :order=>27},
      {:adult=>false,
       :gender=>2,
       :id=>34187,
       :known_for_department=>"Acting",
       :name=>"Chuck Hamilton",
       :original_name=>"Chuck Hamilton",
       :popularity=>3.241,
       :profile_path=>"/yEaR9SLMkQmEoW16Bf99hwLeQqT.jpg",
       :cast_id=>40,
       :character=>"Police Desk Sergeant (uncredited)",
       :credit_id=>"55ee1d44c3a3687d3b00f122",
       :order=>28},
      {:adult=>false,
       :gender=>2,
       :id=>25579,
       :known_for_department=>"Acting",
       :name=>"Chuck Hicks",
       :original_name=>"Chuck Hicks",
       :popularity=>1.4,
       :profile_path=>"/9Nf2YXBz5T8leQcpCTIx492JMJ7.jpg",
       :cast_id=>41,
       :character=>"Ambulance Attendant (uncredited)",
       :credit_id=>"55ee1d7ac3a3686f17005747",
       :order=>29},
      {:adult=>false,
       :gender=>2,
       :id=>1230014,
       :known_for_department=>"Acting",
       :name=>"Nelson Leigh",
       :original_name=>"Nelson Leigh",
       :popularity=>3.095,
       :profile_path=>"/lIQQCKHPRQ8TowO96CsP7rpZS27.jpg",
       :cast_id=>42,
       :character=>"Desk Sergeant #1 (uncredited)",
       :credit_id=>"55ee1dac9251413e3201670e",
       :order=>30},
      {:adult=>false,
       :gender=>2,
       :id=>126997,
       :known_for_department=>"Acting",
       :name=>"David McMahon",
       :original_name=>"David McMahon",
       :popularity=>1.544,
       :profile_path=>"/wBDHqoGFoR7S21EVaSLx7UyccAT.jpg",
       :cast_id=>43,
       :character=>"Crunch's Father (uncredited)",
       :credit_id=>"55ee1dc3c3a36871bf000d29",
       :order=>31},
      {:adult=>false,
       :gender=>0,
       :id=>1234847,
       :known_for_department=>"Acting",
       :name=>"Edward McNally",
       :original_name=>"Edward McNally",
       :popularity=>0.724,
       :profile_path=>nil,
       :cast_id=>44,
       :character=>"Approaching Officer (uncredited)",
       :credit_id=>"55ee1dfec3a3682c6b0157b7",
       :order=>32},
      {:adult=>false,
       :gender=>2,
       :id=>179592,
       :known_for_department=>"Acting",
       :name=>"Peter Miller",
       :original_name=>"Peter Miller",
       :popularity=>1.261,
       :profile_path=>nil,
       :cast_id=>45,
       :character=>"Hoodlum (uncredited)",
       :credit_id=>"55ee1e54c3a3682c6b0157cb",
       :order=>33},
      {:adult=>false,
       :gender=>2,
       :id=>138091,
       :known_for_department=>"Acting",
       :name=>"House Peters Jr.",
       :original_name=>"House Peters Jr.",
       :popularity=>1.474,
       :profile_path=>nil,
       :cast_id=>47,
       :character=>"Officer at Police Station (uncredited)",
       :credit_id=>"55ee1eb7c3a3687d3b00f16c",
       :order=>34},
      {:adult=>false,
       :gender=>2,
       :id=>2765,
       :known_for_department=>"Directing",
       :name=>"Nicholas Ray",
       :original_name=>"Nicholas Ray",
       :popularity=>6.285,
       :profile_path=>"/1K7MdHVN0Ue5oHXRSyD69RoNmmJ.jpg",
       :cast_id=>48,
       :character=>"Man in Last Shot (uncredited)",
       :credit_id=>"55ee1f669251413e2f016159",
       :order=>35},
      {:adult=>false,
       :gender=>2,
       :id=>33743,
       :known_for_department=>"Acting",
       :name=>"Gus Schilling",
       :original_name=>"Gus Schilling",
       :popularity=>1.791,
       :profile_path=>"/stBquPtrUjmdYt79Fb3FUDoXY7r.jpg",
       :cast_id=>49,
       :character=>"Attendant (uncredited)",
       :credit_id=>"55ee1f87c3a36871bf000d80",
       :order=>36},
      {:adult=>false,
       :gender=>2,
       :id=>1208035,
       :known_for_department=>"Acting",
       :name=>"Bert Stevens",
       :original_name=>"Bert Stevens",
       :popularity=>3.216,
       :profile_path=>"/hkjMwqpkbV8hU4Z9GIR6Ct9mzx5.jpg",
       :cast_id=>50,
       :character=>"Police Detective (uncredited)",
       :credit_id=>"55ee1fe59251413e45016408",
       :order=>37},
      {:adult=>false,
       :gender=>2,
       :id=>34448,
       :known_for_department=>"Acting",
       :name=>"Dick Wessel",
       :original_name=>"Dick Wessel",
       :popularity=>4.066,
       :profile_path=>"/dk2lohupEasUkQZitusDCZm2YFx.jpg",
       :cast_id=>51,
       :character=>"Planetarium Guide (uncredited)",
       :credit_id=>"55ee20099251412e070003c1",
       :order=>38},
      {:adult=>false,
       :gender=>2,
       :id=>120070,
       :known_for_department=>"Acting",
       :name=>"Robert B. Williams",
       :original_name=>"Robert B. Williams",
       :popularity=>1.975,
       :profile_path=>"/fDEkRqtvUzwcZd7VzW7A7UZG6ku.jpg",
       :cast_id=>52,
       :character=>"Ed (uncredited)",
       :credit_id=>"55ee202ac3a3682c6b015829",
       :order=>39},
      {:adult=>false,
       :gender=>2,
       :id=>1551605,
       :known_for_department=>"Acting",
       :name=>"Ralph Moratz",
       :original_name=>"Ralph Moratz",
       :popularity=>1.86,
       :profile_path=>"/ax2d7RI6kcHIzV6PBnoE7hafNbs.jpg",
       :cast_id=>56,
       :character=>"Boy at Planetarium (uncredited)",
       :credit_id=>"5676fe0992514179d40065b6",
       :order=>40},
      {:adult=>false,
       :gender=>2,
       :id=>3000319,
       :known_for_department=>"Acting",
       :name=>"Skipper Huerta",
       :original_name=>"Skipper Huerta",
       :popularity=>0.6,
       :profile_path=>nil,
       :cast_id=>64,
       :character=>"Little Boy (uncredited)",
       :credit_id=>"60432ad6d18572002ae6f575",
       :order=>41}],
    :crew=>
     [{:adult=>false,
       :gender=>2,
       :id=>2027,
       :known_for_department=>"Sound",
       :name=>"Leonard Rosenman",
       :original_name=>"Leonard Rosenman",
       :popularity=>0.78,
       :profile_path=>"/f3hxgLgST2hfFkjkiP9hdCcWkj9.jpg",
       :credit_id=>"52fe4228c3a36847f8008787",
       :department=>"Sound",
       :job=>"Original Music Composer"},
      {:adult=>false,
       :gender=>2,
       :id=>2749,
       :known_for_department=>"Acting",
       :name=>"James Dean",
       :original_name=>"James Dean",
       :popularity=>11.552,
       :profile_path=>"/5oaDvEoQssXlDt1KSQVl0M4rgBn.jpg",
       :credit_id=>"643fe9577e403d0508259a3f",
       :department=>"Directing",
       :job=>"Co-Director"},
      {:adult=>false,
       :gender=>2,
       :id=>2764,
       :known_for_department=>"Art",
       :name=>"Malcolm C. Bert",
       :original_name=>"Malcolm C. Bert",
       :popularity=>1.4,
       :profile_path=>nil,
       :credit_id=>"56510ced9251414b0a008857",
       :department=>"Art",
       :job=>"Art Direction"},
      {:adult=>false,
       :gender=>2,
       :id=>2765,
       :known_for_department=>"Directing",
       :name=>"Nicholas Ray",
       :original_name=>"Nicholas Ray",
       :popularity=>6.285,
       :profile_path=>"/1K7MdHVN0Ue5oHXRSyD69RoNmmJ.jpg",
       :credit_id=>"52fe4228c3a36847f8008749",
       :department=>"Directing",
       :job=>"Director"},
      {:adult=>false,
       :gender=>2,
       :id=>2765,
       :known_for_department=>"Directing",
       :name=>"Nicholas Ray",
       :original_name=>"Nicholas Ray",
       :popularity=>6.285,
       :profile_path=>"/1K7MdHVN0Ue5oHXRSyD69RoNmmJ.jpg",
       :credit_id=>"5be9c74a0e0a263bf8046590",
       :department=>"Writing",
       :job=>"Story"},
      {:adult=>false,
       :gender=>2,
       :id=>2766,
       :known_for_department=>"Production",
       :name=>"David Weisbart",
       :original_name=>"David Weisbart",
       :popularity=>1.216,
       :profile_path=>nil,
       :credit_id=>"52fe4228c3a36847f800874f",
       :department=>"Production",
       :job=>"Producer"},
      {:adult=>false,
       :gender=>2,
       :id=>2767,
       :known_for_department=>"Writing",
       :name=>"Irving Shulman",
       :original_name=>"Irving Shulman",
       :popularity=>1.202,
       :profile_path=>nil,
       :credit_id=>"5be9c759c3a3681746041319",
       :department=>"Writing",
       :job=>"Adaptation"},
      {:adult=>false,
       :gender=>2,
       :id=>2768,
       :known_for_department=>"Writing",
       :name=>"Stewart Stern",
       :original_name=>"Stewart Stern",
       :popularity=>2.404,
       :profile_path=>"/nbI4y0QRyKdcxoqZ4uPVixnnJNQ.jpg",
       :credit_id=>"5be9c763c3a368174e0422da",
       :department=>"Writing",
       :job=>"Screenplay"},
      {:adult=>false,
       :gender=>2,
       :id=>2773,
       :known_for_department=>"Editing",
       :name=>"William H. Ziegler",
       :original_name=>"William H. Ziegler",
       :popularity=>1.546,
       :profile_path=>nil,
       :credit_id=>"52fe4228c3a36847f800877b",
       :department=>"Editing",
       :job=>"Editor"},
      {:adult=>false,
       :gender=>2,
       :id=>2774,
       :known_for_department=>"Camera",
       :name=>"Ernest Haller",
       :original_name=>"Ernest Haller",
       :popularity=>1.631,
       :profile_path=>"/mOCqO38x83AF9aJ7iCZ7Qqn9hvr.jpg",
       :credit_id=>"52fe4228c3a36847f8008781",
       :department=>"Camera",
       :job=>"Director of Photography"},
      {:adult=>false,
       :gender=>2,
       :id=>2791,
       :known_for_department=>"Sound",
       :name=>"Stanley Jones",
       :original_name=>"Stanley Jones",
       :popularity=>0.6,
       :profile_path=>nil,
       :credit_id=>"60d7296e109cd00047098167",
       :department=>"Sound",
       :job=>"Sound"},
      {:adult=>false,
       :gender=>2,
       :id=>4313,
       :known_for_department=>"Costume & Make-Up",
       :name=>"Gordon Bau",
       :original_name=>"Gordon Bau",
       :popularity=>2.143,
       :profile_path=>nil,
       :credit_id=>"5f8cc8cfcb802800390866e5",
       :department=>"Costume & Make-Up",
       :job=>"Makeup Supervisor"},
      {:adult=>false,
       :gender=>2,
       :id=>14727,
       :known_for_department=>"Costume & Make-Up",
       :name=>"Moss Mabry",
       :original_name=>"Moss Mabry",
       :popularity=>1.027,
       :profile_path=>nil,
       :credit_id=>"56510d0392514164c00047de",
       :department=>"Costume & Make-Up",
       :job=>"Costume Design"},
      {:adult=>false,
       :gender=>2,
       :id=>85426,
       :known_for_department=>"Acting",
       :name=>"Don Alvarado",
       :original_name=>"Don Alvarado",
       :popularity=>2.175,
       :profile_path=>"/bAaakAh6xFdd4saJMDHoU1uzd88.jpg",
       :credit_id=>"5f8cc91defd3c200393f7993",
       :department=>"Directing",
       :job=>"Assistant Director"},
      {:adult=>false,
       :gender=>0,
       :id=>1137341,
       :known_for_department=>"Art",
       :name=>"William Wallace",
       :original_name=>"William Wallace",
       :popularity=>0.611,
       :profile_path=>nil,
       :credit_id=>"56a1714dc3a36858ce00fe99",
       :department=>"Art",
       :job=>"Set Decoration"},
      {:adult=>false,
       :gender=>0,
       :id=>2633360,
       :known_for_department=>"Production",
       :name=>"Robert Farfan",
       :original_name=>"Robert Farfan",
       :popularity=>0.6,
       :profile_path=>nil,
       :credit_id=>"5f8cc93d392712003727b5d7",
       :department=>"Directing",
       :job=>"Assistant Director"}]
  }
end

def reviews_stub
  {
    :id=>238,
    :page=>1,
    :results=>
     [{:author=>"futuretv",
       :author_details=>{:name=>"", :username=>"futuretv", :avatar_path=>"/https://secure.gravatar.com/avatar/f44259356bf6110070ed799323d539d6.jpg", :rating=>10.0},
       :content=>
        "The Godfather Review by Al Carlson\r\n\r\nThe Godfather is a film considered by most to be one of the greatest ever made. From The American Film Institute to as voted by users on the Internet Movie Database (IMDB) it is consider to be one of the best. As a film that ranks as high as other masterpieces including Citizen Kane, Pulp Fiction and 12 Angry Men, The Godfather is an exceptional piece of cinema excellence that is flawless and is simply the pinnacle crime drama.\r\nThe Godfather revolves around the Corleone’s, an Italian family with deep roots in the New York City mafia. The head of the Corleone’s is Don Vito Corleone, a man who takes care of his family and demands respect in return. His son Michael however, who just returned home from World War II, doesn’t want to become involved with the family business. The Sollozzo’s, a family of drug dealers, confront Don and request protection in exchange for profits from the Sollozzo’s drug sales. But Don declines the offer, for he is against selling narcotics. The rejected offer starts what turns into an all out mafia war between the two families with Michael diving deep into the mafia lifestyle.\r\nThe characters are portrayed by a legendary all-star cast including Marlon Brando as Don, Al Pacino as his son Michael and James Caan as Don’s oldest son Sonny. The casting for this film has been considered by many to be the best casted film in history for their astonishing performances. All three main actors were nominated for an academy award, but only Marlon Brando won an Oscar for best actor in a leading role. It’s fascinating to watch how these characters change over the course of the movie, with one in particular changing drastically.\r\nDirecter Francis Ford Coppola, being raised in an Italian-American family in New York, understood Italian culture exceptionally and made the film very authentically. Everything from the wedding dances to the cuisine to the terms used by the characters in Sicilian come from Coppola’s first-hand knowledge of Italian-American culture. Italian composer Nino Rota did an outstanding job making the soundtrack for the film, despite not getting the Oscar for best music (but he did win an Oscar for his work in the sequel, The Godfather: Part II). Virtually everyone recognizes that iconic trumpet solo once it starts playing. He also wrote the score for another great Italian film 8 1/2. \r\nThis film should be immediately followed up by it’s sequel, The Godfather: Part II, which also won best picture. The series still holds the title of most best picture awards for a film series to this day. They’re both flawless crime dramas and have earned their titles as some of the best pieces of cinema ever. I will guarantee you won’t be able to see this film only once, as it gets better after continual viewings. There is really nothing more to add other than if you haven’t seen this movie yet, it’s about time you did. The Godfather is a movie you can’t refuse.",
       :created_at=>"2014-04-10T20:09:40.500Z",
       :id=>"5346fa840e0a265ffa001e20",
       :updated_at=>"2021-06-23T15:57:25.895Z",
       :url=>"https://www.themoviedb.org/review/5346fa840e0a265ffa001e20"},
      {:author=>"crastana",
       :author_details=>{:name=>"", :username=>"crastana", :avatar_path=>"/https://secure.gravatar.com/avatar/87b1f10dd7dae245ac84657537983336.jpg", :rating=>10.0},
       :content=>
        "The best movie ever...\r\nA masterpiece by the young and talented Francis Ford Coppola, about a Mob family and their drama, the story telling is perfect, the acting good, sometimes a little over the top in the case of Thalia Shire (the sister of the director)\r\n\r\nThe 70's were the best years for Hollywood.",
       :created_at=>"2022-07-18T23:18:07.748Z",
       :id=>"62d5ea2fe93e95095cbddefe",
       :updated_at=>"2022-07-26T14:21:07.910Z",
       :url=>"https://www.themoviedb.org/review/62d5ea2fe93e95095cbddefe"},
      {:author=>"drystyx",
       :author_details=>{:name=>"", :username=>"drystyx", :avatar_path=>"/hLLsAvAnVT0cFU7JuuaaItTWXv8.jpg", :rating=>1.0},
       :content=>
        "While I'm writing this, The Godfather is still beloved by people who love it simply because they are told they have to love it. \r\nIt's written by a mobster with the sole intention of depicting the lead mobsters as demi gods. Every line and every scene in the movie and the book is meant to intimidate people into thinking the \"Mafia\" and really any mob, is a supernatural force.\r\nThis is a movie glorifying control freaks, and most critics are control freaks, and most critics are either in the mob or think they can join the mob.\r\nThe movie itself is dull and totally uninspiring, not to mention totally uninspired. For fifty years, the sheep have been cowing to the control freaks who tell them to love this movie that degrades them. \r\nThere just isn't anything favorable about this movie. It owes its success to people who have interests in the movie or think they can get brownie points with such people. It's totally Hollywood in its depressing nature, and even in the seventies it was a formula film.",
       :created_at=>"2023-04-02T03:49:51.130Z",
       :id=>"6428fb5f60975000eb3e9c39",
       :updated_at=>"2023-04-03T16:45:04.834Z",
       :url=>"https://www.themoviedb.org/review/6428fb5f60975000eb3e9c39"},
      {:author=>"CinemaSerf",
       :author_details=>{:name=>"CinemaSerf", :username=>"Geronimo1967", :avatar_path=>"/1kks3YnVkpyQxzw36CObFPvhL5f.jpg", :rating=>7.0},
       :content=>
        "When you get a story written quite this magnificently it would take an extreme amateur to screw it up - and Francis Ford Coppola is no amateur. Marlon Brando, Al Pacino, James Caan and Robert Duvall represent the epitome of guile, sophistication, loyalty, honour and brutality in this self-adapted Mario Puzo story of the unambiguously ambitious \"Corleone\" family - they start with nothing and so the only way is up; however and whatever they need to do to get there. The characterisations are layered and colourful; Diane Keaton has no idea what she's getting herself into! John Cazale is great as the spineless brother \"Fredo\" too. Once again, Nino Rota pulls out all the stops to give this a score that helps cement this film's place as amongst the best ever made. My only criticism, and it is slight at that, is that the audio mix could have done with a bit of a boost. Much of the dialogue - especially from Brando - verges on the inaudible at times.",
       :created_at=>"2023-05-28T11:02:44.814Z",
       :id=>"647334d4be2d490116c935bd",
       :updated_at=>"2023-05-28T11:02:44.905Z",
       :url=>"https://www.themoviedb.org/review/647334d4be2d490116c935bd"},
      {:author=>"Suresh Chidurala",
       :author_details=>{:name=>"Suresh Chidurala", :username=>"Suresh17511", :avatar_path=>"/https://secure.gravatar.com/avatar/4965583abc47850975522bdfcad0c325.jpg", :rating=>9.0},
       :content=>"Great Movie **Ever**",
       :created_at=>"2023-06-11T09:30:35.855Z",
       :id=>"6485943be375c000c5282981",
       :updated_at=>"2023-06-13T15:48:33.210Z",
       :url=>"https://www.themoviedb.org/review/6485943be375c000c5282981"}],
    :total_pages=>1,
    :total_results=>5
  }
end